# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native' # This path is likely to be `../node_modules/react-native` in your own project.
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'Firebase/Auth', '~> 5.7.0'
  pod 'Firebase/Core', '~> 5.7.0'
  pod 'Firebase/Firestore', '~> 5.7.0'

  # Pods for TwitterApp

  target 'TwitterApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TwitterApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TwitterApp-tvOS

end
